importing numpy

In [1]:
import numpy as np

time taken by list

In [2]:
from time import process_time

time taken

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time ()

python_list = [i+5 for i in python_list]

end_time = process_time ()

print (end_time - start_time)

0.0015040189999995235


using numpy array

In [4]:
np_array = np.array([i for i in range (10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0003616239999999493


numpy array

In [5]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

2d array

In [6]:
b = np.array ([ (1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

placeholders

In [7]:
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [9]:
#identity matrix
j = np.eye((5))
print(j)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
#random nos
s = np.random.random((3,3))
print(s)

[[0.58894574 0.9197838  0.74337922]
 [0.45168423 0.18762597 0.10617647]
 [0.376405   0.37807743 0.10263937]]


random integer values array within a specific range

In [11]:
c = np.random.randint(10,100,(3,3))
print(c)

[[71 90 95]
 [48 47 57]
 [93 74 70]]


array of evenly spaced values --> specifying the numbers required

In [12]:
d = np.linspace (10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [13]:
# using arrange ie specifies the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


convert list to array

In [14]:
list2 = [10, 20, 30, 20, 50]

np_array = np.asarray(list2)
print(np_array)

[10 20 30 20 50]


analysis of the array

In [15]:
c = np.random.randint(10,100,(3,3))
print(c)

[[12 32 20]
 [82 19 80]
 [23 27 27]]


In [16]:
print(c.shape)

(3, 3)


In [17]:
print(c.ndim)

2


In [18]:
print(c.size)

9


In [19]:
print(c.dtype)

int64


operations on np array

In [20]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
#concatenete
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [21]:
a = np.random.randint (0,10, (2,2))
b = np.random.randint (10,20, (2,2))

print(a)
print(b)

[[3 1]
 [5 5]]
[[15 13]
 [19 13]]


In [22]:
print(a-b)

print(a*b)

print(a/b)

[[-12 -12]
 [-14  -8]]
[[45 13]
 [95 65]]
[[0.2        0.07692308]
 [0.26315789 0.38461538]]


array manipulation

In [23]:
 w = np.random.randint(0,10, (2,3))
 print(w)

[[7 2 6]
 [2 4 8]]


In [24]:
# transpose
trans = np.transpose (w)
print (trans)
print (trans.shape)

[[7 2]
 [2 4]
 [6 8]]
(3, 2)


In [25]:
print(w.T)

[[7 2]
 [2 4]
 [6 8]]


reshape matrix

In [26]:
v = w.reshape(3,2)
print(v)

[[7 2]
 [6 2]
 [4 8]]
